---
# Staging/Test Inventory for Cisco STIG Compliance
# Use this for testing before production deployment

all:
  children:
    cisco_devices:
      children:
        cisco_routers:
          hosts:
            # Add test routers here
            # test_router01:
            #   ansible_host: 10.0.0.1

        cisco_switches:
          hosts:
            # Add test switches here
            # test_switch01:
            #   ansible_host: 10.0.0.2

      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_become: yes
        ansible_become_method: enable
