---
# Production Inventory for Cisco STIG Compliance
# Add your devices here

all:
  children:
    cisco_devices:
      children:
        cisco_routers:
          hosts:
            # Example router entries - replace with your actual devices
            # router01:
            #   ansible_host: 192.168.1.1
            # router02:
            #   ansible_host: 192.168.1.2

        cisco_switches:
          hosts:
            # Example switch entries - replace with your actual devices
            # switch01:
            #   ansible_host: 192.168.2.1
            # switch02:
            #   ansible_host: 192.168.2.2

        cisco_layer3_switches:
          hosts:
            # Example L3 switch entries
            # l3switch01:
            #   ansible_host: 192.168.3.1

      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_become: yes
        ansible_become_method: enable

    # Optional: Organize by location
    datacenter:
      children:
        dc_core:
          hosts: {}
        dc_distribution:
          hosts: {}
        dc_access:
          hosts: {}

    # Optional: Organize by environment
    network_tiers:
      children:
        core:
          hosts: {}
        distribution:
          hosts: {}
        access:
          hosts: {}
